### ISSUE TITLE
Device Information makes no sense

### ISSUE THREAD

**Issue by dwestness** [teamviewer/TeamViewerPS#10]
Steps to reproduce:
$Devices = Get-TeamViewerDevice
$Devices | Select-Object Id, Name, LastSeenAt, OnlineState

The output of this results in a list of Devices in my teamviewer account, however i would say about half of them have no "Last Seen At" date field at all. Others indicate that they were last seen ~ months ago (but also reflect them as "Online" currently.
We have about 500 systems online right now and seen to report the Last Seen At time correctly (shows today at various timestamps... but they all show their status as "Offline"

I don't know what do to with this information or how to interpret it properly

**Comment by danieljoos** [comment]
Hi,

The `LastSeenAt` field is only set for devices that are assigned to the current account (which has created the API token). This could explain the devices without that information.
Having online devices that show a `LastSeenAt` field sounds like an issue in the TeamViewer Web API (used by the `TeamViewerPS` module). I will take this point with me and create a corresponding internal issue against the Web API on our side.

Best regards,
Daniel

**Comment by ChristianJ-TV** [comment]
"Last Seen" of devices (MDv2) was added with [v1.5.0](https://github.com/teamviewer/TeamViewerPS/releases/tag/v1.5.0)
