### ISSUE TITLE
FeateureRequest: Allow MSI downloads with Invoke-TeamViewerPackageDownload

### ISSUE THREAD

**Issue by NRL-LEastham** [teamviewer/TeamViewerPS#16]
Hi,

As part of my Intune dployment script i have to keep supplying the latest MSIs and repackaging it, I use the custom parameters so need the MSI. It would be great if I could authenticate with the API token to enable access to the latest MSI versions. This would mean I could run the invoke command at the beginning of the sctipt and know it's always running the latest MSI on install.
If there's other ways to acheive this please let me know.

Thanks,
Lee

**Comment by ChristianJ-TV** [comment]
Hello @NRL-LEastham,

this will be possbile with version 2.

Kind regards,
Christian

**Comment by NRL-LEastham** [comment]
@ChristianJ-TV you've closed this but I can't see any cmdlet that satisfies it in the recent V2 release. I still have to manually go to the website and download the latest MSIs to repackage the deployment.  Please can you advise which  cmdlet does this or re-open this issue?
