### ISSUE TITLE
How to assign a TeamViewer host to an account?

### ISSUE THREAD

**Issue by cansik** [teamviewer/TeamViewerPS#22]
Currently I have to find the TeamViewer installation path and run the TeamViewer.exe with the `assignment` parameter and `assignment ID` (rel. [assign-a-device-to-your-company](https://community.teamviewer.com/English/kb/articles/108805-assign-a-device-to-your-company)). It would be great to be able to use the COM interface for the assignment instead. I tried to find a way to assign it through the powershell COM API, but it seems that this is not support (and `MachineSettings` as well as `UserSettings`  are not implement atm).

Is there a way to use the COM interface to assign a machine to an account automatically?

**Comment by ChristianJ-TV** [comment]
Hello @cansik,

thank you for your post and question.

We are planning a major release of TeamViewerPS in autumn (no guarantee) that will include assignment commands.

The COM API unfortunately does not support the assignment functionality.
