### ISSUE TITLE
Add-TeamviewerUserGroupMember - Adding only one Member - Error converting value 123456543 to type 'system.Collection.Generic.List`1[System.Uint32]'

### ISSUE THREAD

**Issue by ABrauser** [teamviewer/TeamViewerPS#24]
**Summary**
It is not possible to add only one member to a userGroup in Teamviewer over the Powershell Module

Add-TeamviewerUserGroupMember -id 1234 -member @(12323523423)

We get the error message:

Add-TeamViewerUserGroupMember : Error converting value 123123123 to type 'System.Collections.Generic.List`1[System.UInt32]'. Path '', line 1, position 9.  (invalid_request)
In Zeile:1 Zeichen:1
+ Add-TeamViewerUserGroupMember -Id 1234 -Member @(123123123)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-TeamViewerUserGroupMember], RuntimeException
    + FullyQualifiedErrorId : TeamViewerRestError,Add-TeamViewerUserGroupMember

**Expected Behavior**
The user should be added. Interesstingly if you use two member in the Array it works:
Add-TeamviewerUserGroupMember -id 1234 -member @(123523423, 3012340)

**Comment by ChristianJ-TV** [comment]
Hello @ABrauser,

thank you for your bug report.

We've already worked on this issue and released a fix just today with version 1.5.1.
The new release will be also pushed to the Powershell Gallery soon.
