### ISSUE TITLE
"Last_seen" for Managed Devices

### ISSUE THREAD

**Issue by duczz** [teamviewer/TeamViewerPS#53]
Hey,

is it possible to add the "last_seen" properties from Get-TeamViewerDevice.ps1 in Get-TeamViewerManagedDevice.ps1 too?

**Comment by ChristianJ-TV** [comment]
Hello @duczz,

just tested it with version 1.5.2 of the module.
Get-TeamViewerManagedDevice already includes the "LastSeenAt" property.

This property depends on the online state and also needs a client version from this year (March?).

**Comment by duczz** [comment]
Im using Teamviewer Host V15.47.3 H and there are only these objects (no "LastSeenAt"):

PolicyId
IsOnline
Name
Id
TeamViewerId

**Comment by NRL-LEastham** [comment]
@ChristianJ-TV This shouldn't be closed as you checked an older release of the module. In the current version module it does not return LastSeenAt, just IsOnline.
