### ISSUE TITLE
Group

### ISSUE THREAD

**Issue by duczz** [teamviewer/TeamViewerPS#55]
is there a way to overwrite a consistend group from an device?

Teamviewer is installed in Group "installed", now i wanna change it to group "changed"
currently my way is delete the current group and add the new one, exists a overwrite methode for this?

**Comment by ChristianJ-TV** [comment]
Hey @duczz,

you don't need to delete groups to just move a device into another one.

If you are using managed groups, you can use `Add-TeamViewerManagedDevice`, `Remove-TeamViewerManagedDevice`, or `Set-TeamViewerManagedDevice` to achieve this.

**Comment by duczz** [comment]
When i try these i get thise Error:
Set-TeamViewerManagedDevice -Device xxxxxxxxxxxxxxxxxxxxxxx -ManagedGroup xxxxxxxxxxxxxxxxxxxxxx

Set-TeamViewerManagedDevice : Invalid Managed Group identifier specified. Device is not part of the managed group. (invalid_request)

**Comment by AlexandrosAlexiou** [comment]
> When i try these i get thise Error: Set-TeamViewerManagedDevice -Device xxxxxxxxxxxxxxxxxxxxxxx -ManagedGroup xxxxxxxxxxxxxxxxxxxxxx
> 
> Set-TeamViewerManagedDevice : Invalid Managed Group identifier specified. Device is not part of the managed group. (invalid_request)

This command actually sets the policy of the device specified to that of the managed group specified.
In short, the device inherits the policy from the group but this device has to be part of that specific group.

**Comment by duczz** [comment]
@AlexandrosAlexiou Okay, but how can i set so the device to a group? With add i add a group to a existing group on the device, i wanna overwrite it directly

**Comment by AlexandrosAlexiou** [comment]
> @AlexandrosAlexiou Okay, but how can i set so the device to a group? With add i add a group to a existing group on the device, i wanna overwrite it directly

Sorry, I do not understand what `overwrite` refers to. Can you re-explain what you are trying to achieve here?

**Comment by duczz** [comment]
Sorry for my bad english :(
1 PC has a group, this group should be join in a other group, currently i find only a way to add more groups but not direct way to replace these current group with an other, i need always the way to delete the existing group and add than the group witch i want.
