### ISSUE TITLE
Version 2.0.0 - PSGallery Release Date?

### ISSUE THREAD

**Issue by EskimoRuler** [teamviewer/TeamViewerPS#58]
**Summary**
Is there an ETA for the Version 2.0.0 release within the PSGallery?

I see the changelog shows the 2.0.0 release was dated 9-13-2023, but the PSGallery only has 1.5.2.

**Comment by ChristianJ-TV** [comment]
Hey @EskimoRuler,

there is no fix date yet, but I would say in ~ two weeks.
We are still working on last features, optimizations and bugfixes.

**Comment by EskimoRuler** [comment]
> Hey @EskimoRuler,
> 
> there is no fix date yet, but I would say in ~ two weeks. We are still working on last features, optimizations and bugfixes.

Hey @ChristianJ-TV,

Thanks for the update, looking forward to it!
