### ISSUE TITLE
Deactivating a user does not seem to work[Bug] 

### ISSUE THREAD

**Issue by fpsacha** [teamviewer/TeamViewerPS#71]
**Summary**
Tried to deactivate a user using the ID and i get the message : Set-TeamViewerUser: The given input does not change the user.
but activating it with $true is working. $false is not working.

**Expected Behavior**
The user to be deactivated like he is activated with $true

**Setps To Reproduce**
followed the example 3 from here. The user exist and i am using the API from https://login.teamviewer.com/nav/managecompany/apps with all rights.
(https://github.com/teamviewer/TeamViewerPS/blob/main/Docs/Help/Set-TeamViewerUser.md)

**Attachments**
If applicable, provide files (e.g. configuration, log files, screenshots) to help explain your problem.

**Comment by ChristianJ-TV** [comment]
Hello @fpsacha,

thanks for bringing this up.
I can confirm the issue. We will look into it.

This way it's working:
`Set-TeamViewerUser -User u123456789 -Active $false`

**Comment by fpsacha** [comment]
> Hello @fpsacha,
> 
> thanks for bringing this up. I can confirm the issue. We will look into it.
> 
> This way it's working: `Set-TeamViewerUser -User u123456789 -Active $false`

Indeed i just confirmed and it works with -Active $false.

Thanks. Awesome module by the way.
